# Generated by Django 2.2.1 on 2019-05-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0003_auto_20190515_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='subcategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashmanage.Subcategory'),
        ),
    ]
