# Generated by Django 2.2.1 on 2019-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0007_auto_20190516_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
