# Generated by Django 2.2.1 on 2019-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0011_auto_20190516_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='options',
            field=models.TextField(choices=[('1', 'Wpływ'), ('2', 'Wydatek')], default='2'),
        ),
    ]
