# Generated by Django 2.2.1 on 2019-05-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0012_auto_20190516_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanage.Account'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanage.Category'),
        ),
    ]
