# Generated by Django 2.2.1 on 2019-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0014_auto_20190516_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_amount',
            field=models.FloatField(),
        ),
    ]
