# Generated by Django 2.2.1 on 2019-05-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanage', '0016_auto_20190517_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashmanage.Subcategory'),
        ),
    ]
